/**
 * AUTO-GENERATED by scripts/generate-inventory-guide-data.mjs — do not edit by hand.
 * Source: PreluraSwift/HELP_CENTRE_FEATURE_INVENTORY.md (§1–§5, §8, §9).
 */

export type InventoryManifestTableBlock = {
  type: "table";
  headers: string[] | null;
  rows: string[][];
};

export type InventoryManifestBlock =
  | { type: "paragraph"; text: string }
  | { type: "h3"; text: string }
  | { type: "list"; items: string[] }
  | { type: "ordered"; items: string[] }
  | { type: "code"; text: string }
  | InventoryManifestTableBlock;

export type InventoryManifestSection = {
  id: string;
  title: string;
  blocks: InventoryManifestBlock[];
};

export const INVENTORY_DOC_PROLOGUE: string[] = [
  "This document is the machine-assisted manifest described in the help-centre plan: **Views**, **navigation**, **modals**, **services**, a **persona QA matrix**, an **authoring template**, and **DNS / URL** notes. Use it as the long “notepad” input for drafting articles.",
  "**Canonical help host (in-app):** `https://help.mywearhouseapp.com` — see [`Constants.swift`](Prelura-swift/Utilities/Constants.swift) (`helpCentreBaseURL`). Legal pages remain on `https://mywearhouse.co.uk` (`publicWebsiteBaseURL`)."
];

export const INVENTORY_MANIFEST_SECTIONS: InventoryManifestSection[] = [
  {
    "id": "manifest-1-dns-and-tls-for-help-mywearhouseapp-com",
    "title": "1. DNS and TLS for `help.mywearhouseapp.com`",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Operational checklist (no automation here):"
      },
      {
        "type": "ordered",
        "items": [
          "In DNS for `mywearhouseapp.com`, create **`help`** as a **CNAME** to your hosting provider’s target (or **A/ALIAS** if they require it).",
          "In the hosting dashboard (Vercel, Netlify, Cloudflare Pages, etc.), add **custom domain** `help.mywearhouseapp.com` and wait for verification.",
          "Enable **HTTPS** (usually automatic once DNS resolves).",
          "Publish help content at the paths referenced in `Constants.help*` URLs (see §7), or add redirects from old `mywearhouse.co.uk/help/...` URLs if needed.",
          "Smoke-test each URL in Safari (cookies, mixed content, mobile viewport)."
        ]
      },
      {
        "type": "paragraph",
        "text": "**Note:** Apex marketing domain in code is `mywearhouse.co.uk`; your requested subdomain uses `mywearhouseapp.com`. Ensure both DNS zones and TLS are correct for whichever domains you own."
      }
    ]
  },
  {
    "id": "manifest-2-app-shell-and-navigation",
    "title": "2. App shell and navigation",
    "blocks": [
      {
        "type": "h3",
        "text": "2.1 Root flow"
      },
      {
        "type": "list",
        "items": [
          "**Splash:** [`SplashView.swift`](Prelura-swift/Views/SplashView.swift) → then [`AppearanceRootView`](Prelura-swift/Prelura_swiftApp.swift) (theme + language identity).",
          "**Unauthenticated:** [`LoginView`](Prelura-swift/Views/Auth/LoginView.swift) (with signup / forgot password / verification flows).",
          "**Authenticated or guest:** [`MainTabView`](Prelura-swift/Prelura_swiftApp.swift) — five tabs.",
          "**Account restricted:** [`AccountRestrictionOverlayView`](Prelura-swift/Views/Auth/AccountRestrictionOverlayView.swift) when `authService.isAccountRestricted`.",
          "**Post-login onboarding:** fullScreenCover [`OnboardingFlowView`](Prelura-swift/Views/Onboarding/OnboardingFlowView.swift).",
          "**Deep link / notification item:** `fullScreenCover` [`DeepLinkOverlayView`](Prelura-swift/Views/DeepLink/DeepLinkOverlayView.swift) via `AppRouter.pendingItem`."
        ]
      },
      {
        "type": "h3",
        "text": "2.2 Tabs (`MainTabView`)"
      },
      {
        "type": "table",
        "headers": [
          "Index",
          "Tab",
          "Root view",
          "Navigation wrapper"
        ],
        "rows": [
          [
            "0",
            "Home",
            "`HomeView`",
            "`HomeNavigation`"
          ],
          [
            "1",
            "Discover",
            "`DiscoverView`",
            "`DiscoverNavigation`"
          ],
          [
            "2",
            "Sell",
            "`SellView`",
            "`SellNavigation`"
          ],
          [
            "3",
            "Inbox",
            "`ChatListView`",
            "`InboxNavigation`"
          ],
          [
            "4",
            "Profile",
            "`ProfileView`",
            "`ProfileNavigation`"
          ]
        ]
      },
      {
        "type": "paragraph",
        "text": "Source: [`Prelura_swiftApp.swift`](Prelura-swift/Prelura_swiftApp.swift), [`NavigationContainers.swift`](Prelura-swift/NavigationContainers.swift)."
      },
      {
        "type": "h3",
        "text": "2.3 `AppRoute` (shared push destinations)"
      },
      {
        "type": "paragraph",
        "text": "Defined in [`AppRoute.swift`](Prelura-swift/AppRoute.swift):"
      },
      {
        "type": "table",
        "headers": [
          "Case",
          "Destination",
          "Home",
          "Discover",
          "Inbox",
          "Profile"
        ],
        "rows": [
          [
            "`itemDetail(Item)`",
            "`ItemDetailView`",
            "Yes",
            "Yes",
            "—",
            "Yes"
          ],
          [
            "`conversation(Conversation, isArchived:)`",
            "`ChatDetailView`",
            "—",
            "—",
            "Yes",
            "—"
          ],
          [
            "`menu(MenuContext)`",
            "`MenuView`",
            "—",
            "—",
            "—",
            "Yes"
          ],
          [
            "`reviews(username:rating:)`",
            "`ReviewsView`",
            "Yes",
            "Yes",
            "Yes",
            "Yes"
          ]
        ]
      },
      {
        "type": "h3",
        "text": "2.4 Profile hub menu (`MenuView`)"
      },
      {
        "type": "paragraph",
        "text": "From [`MenuView.swift`](Prelura-swift/Views/Menu/MenuView.swift), user-visible entries (settings gear opens [`SettingsMenuView`](Prelura-swift/Views/Profile/ProfileMenuView.swift)):"
      },
      {
        "type": "list",
        "items": [
          "Lookbook (beta) → `LookbookView`",
          "Seller dashboard → `ShopValueView`",
          "Orders → `MyOrdersView`",
          "Favourites → `MyFavouritesView`",
          "Multi-buy discounts → `MultiBuyDiscountView`",
          "Vacation Mode → `VacationModeView`",
          "Invite Friend → `InviteFriendView`",
          "Help Centre → `HelpCentreView`",
          "About WEARHOUSE → `AboutWearhouseMenuView` (`HowToUseWearhouseView`, `LegalInformationView`)",
          "Logout (confirm alert)"
        ]
      },
      {
        "type": "paragraph",
        "text": "**DEBUG builds only:** `DebugMenuView` link."
      },
      {
        "type": "h3",
        "text": "2.5 Settings destinations (`MenuDestination`)"
      },
      {
        "type": "paragraph",
        "text": "Enum in [`MenuDestination.swift`](Prelura-swift/Views/Profile/MenuDestination.swift) mirrors Flutter-style settings: account, shipping, appearance, profile, payments, postage, security/privacy, identity, push/email notifications, admin actions."
      }
    ]
  },
  {
    "id": "manifest-3-view-manifest-all-views-swift",
    "title": "3. View manifest (all `Views/**/*.swift`)",
    "blocks": [
      {
        "type": "paragraph",
        "text": "**Legend:** `user` = ship in help centre; `component` = UI building block; `debug` = internal / DEBUG; `admin` = staff-only surfaces."
      },
      {
        "type": "h3",
        "text": "3.1 By folder (summary)"
      },
      {
        "type": "table",
        "headers": [
          "Folder",
          "Role"
        ],
        "rows": [
          [
            "`AIChat/`",
            "AI support / Ann chat (`user`)"
          ],
          [
            "`Auth/`",
            "Login, signup, password, verification, restriction overlay (`user`)"
          ],
          [
            "`Browse/`",
            "Browse / feed-related (`user`)"
          ],
          [
            "`Chat/`",
            "Inbox thread, order help, reactions, issue detail (`user`)"
          ],
          [
            "`Components/`",
            "Reusable controls, shimmer, tab bar, guest prompt (`component`; document only if user-visible, e.g. guest sign-in prompt)"
          ],
          [
            "`DeepLink/`",
            "Full-screen deep link item (`user`)"
          ],
          [
            "`Discover/`",
            "Discover, lookbook feed, search members, analytics (`user`; feed helpers may be `component`)"
          ],
          [
            "`FilteredProducts/`",
            "Filtered listings, Shop All bag (`user`)"
          ],
          [
            "`Home/`",
            "Home feed (`user`)"
          ],
          [
            "`Inbox/`",
            "Legacy/alternate inbox shell if used (`user` if reachable)"
          ],
          [
            "`ItemDetail/`",
            "Product page, send offer (`user`)"
          ],
          [
            "`Menu/`",
            "Menu subtree, orders, admin tools, many **debug** screens"
          ],
          [
            "`Notifications/`",
            "Bell / notifications list (`user`)"
          ],
          [
            "`Onboarding/`",
            "First-run flows (`user`)"
          ],
          [
            "`Payment/`",
            "Checkout / success (`user`)"
          ],
          [
            "`Profile/`",
            "Profile, followers, reviews, cart, menu (`user`)"
          ],
          [
            "`Report/`",
            "Report user (`user`)"
          ],
          [
            "`Sell/`",
            "Listing creation / drafts (`user` + editor `component`)"
          ],
          [
            "`Settings/`",
            "Account settings subtree (`user`; `AdminMenuView` = `admin`)"
          ]
        ]
      },
      {
        "type": "h3",
        "text": "3.2 Tagged list: admin and debug (exclude from consumer help)"
      },
      {
        "type": "paragraph",
        "text": "**Admin / staff (`admin`):**"
      },
      {
        "type": "list",
        "items": [
          "`Views/Menu/AdminAllOrdersView.swift`",
          "`Views/Menu/AdminDashboardView.swift`",
          "`Views/Menu/AdminOrderIssuesView.swift`",
          "`Views/Menu/AdminReportsView.swift`",
          "`Views/Settings/AdminMenuView.swift`"
        ]
      },
      {
        "type": "paragraph",
        "text": "**Debug / internal (`debug`) — filenames indicate engineering tools:**"
      },
      {
        "type": "list",
        "items": [
          "`Views/Menu/AnimatedScreenDebugView.swift`",
          "`Views/Menu/BlackScreenProfileView.swift`",
          "`Views/Menu/BlackScreensMenuView.swift`",
          "`Views/Menu/ChatThreadLiveUpdateDebugView.swift`",
          "`Views/Menu/DebugLikeButtonOnlyView.swift`",
          "`Views/Menu/DebugLookbookFeedSandboxView.swift`",
          "`Views/Menu/DebugMenuView.swift`",
          "`Views/Menu/DebugSandboxLikeButton.swift`",
          "`Views/Menu/FeedNetworkBannerDebugView.swift`",
          "`Views/Menu/GlassEffectTransitionView.swift`",
          "`Views/Menu/GlassMaterialsView.swift`",
          "`Views/Menu/MessageChatPushTraceDebugView.swift`",
          "`Views/Menu/MessageDeliveryDebugView.swift`",
          "`Views/Menu/NetworkErrorPresentationDebugView.swift`",
          "`Views/Menu/NotificationTypeMatrixDebugView.swift`",
          "`Views/Menu/OrderChatMockDebugView.swift`",
          "`Views/Menu/OrderScreenDebugView.swift`",
          "`Views/Menu/PushDiagnosticsView.swift`",
          "`Views/Menu/WebSocketConnectionDebugView.swift`"
        ]
      },
      {
        "type": "h3",
        "text": "3.3 Complete file list (149 files)"
      },
      {
        "type": "paragraph",
        "text": "Each line: **path** — **tag**"
      },
      {
        "type": "list",
        "items": [
          "`Views/AIChat/AIChatView.swift` — user",
          "`Views/AIChat/AnnChatView.swift` — user",
          "`Views/Auth/AccountRestrictionOverlayView.swift` — user",
          "`Views/Auth/EmailSentView.swift` — user",
          "`Views/Auth/EmailVerificationCodeView.swift` — user",
          "`Views/Auth/ForgotPasswordView.swift` — user",
          "`Views/Auth/LoginView.swift` — user",
          "`Views/Auth/NewPasswordView.swift` — user",
          "`Views/Auth/SignupView.swift` — user",
          "`Views/Auth/VerifyUserView.swift` — user",
          "`Views/Browse/BrowseView.swift` — user",
          "`Views/Chat/ChatDetailView.swift` — user",
          "`Views/Chat/ChatListView.swift` — user",
          "`Views/Chat/ItemNotAsDescribedHelpView.swift` — user",
          "`Views/Chat/ItemNotReceivedHelpViews.swift` — user",
          "`Views/Chat/OrderHelpView.swift` — user",
          "`Views/Chat/OrderIssueDetailView.swift` — user",
          "`Views/Chat/SellerOrderIssueDetailsView.swift` — user",
          "`Views/Chat/WhatsAppStyleReactionOverlay.swift` — component",
          "`Views/Components/BorderGlassButton.swift` — component",
          "`Views/Components/CircleCloseButton.swift` — component",
          "`Views/Components/ContentDivider.swift` — component",
          "`Views/Components/CustomTabBarView.swift` — component",
          "`Views/Components/DiscoverSearchField.swift` — component",
          "`Views/Components/DiscoverShimmerView.swift` — component",
          "`Views/Components/FeedNetworkBannerView.swift` — component",
          "`Views/Components/FeedSearchField.swift` — component",
          "`Views/Components/FeedShimmerView.swift` — component",
          "`Views/Components/GlassButton.swift` — component",
          "`Views/Components/GlassCard.swift` — component",
          "`Views/Components/GlassNavigationBar.swift` — component",
          "`Views/Components/GuestSignInPromptView.swift` — component (user-visible)",
          "`Views/Components/ImageShimmerPlaceholder.swift` — component",
          "`Views/Components/InboxShimmerView.swift` — component",
          "`Views/Components/ItemCard.swift` — component",
          "`Views/Components/LikeButtonView.swift` — component",
          "`Views/Components/LocationSuggestionField.swift` — component",
          "`Views/Components/OptionsSheet.swift` — component",
          "`Views/Components/PillTag.swift` — component",
          "`Views/Components/PrimaryButtonBar.swift` — component",
          "`Views/Components/PrimaryGlassButton.swift` — component",
          "`Views/Components/ProfileShimmerView.swift` — component",
          "`Views/Components/RetryAsyncImage.swift` — component",
          "`Views/Components/SettingsTextField.swift` — component",
          "`Views/Components/VideoBackgroundView.swift` — component",
          "`Views/Components/WearhouseWordmarkView.swift` — component",
          "`Views/Components/WebView.swift` — component",
          "`Views/DeepLink/DeepLinkOverlayView.swift` — user",
          "`Views/Discover/DiscoverView.swift` — user",
          "`Views/Discover/LookbookAnalyticsView.swift` — user",
          "`Views/Discover/LookbookFeedAssets.swift` — component",
          "`Views/Discover/LookbookFeedScrollTouchFix.swift` — component",
          "`Views/Discover/LookbookSettingsView.swift` — user",
          "`Views/Discover/LookbookView.swift` — user",
          "`Views/Discover/SearchMembersView.swift` — user",
          "`Views/FilteredProducts/FilteredProductsView.swift` — user",
          "`Views/FilteredProducts/ShopAllBagView.swift` — user",
          "`Views/Home/HomeView.swift` — user",
          "`Views/Inbox/InboxView.swift` — user",
          "`Views/ItemDetail/ItemDetailView.swift` — user",
          "`Views/ItemDetail/SendOfferSheet.swift` — user",
          "`Views/Menu/AdminAllOrdersView.swift` — admin",
          "`Views/Menu/AdminDashboardView.swift` — admin",
          "`Views/Menu/AdminOrderIssuesView.swift` — admin",
          "`Views/Menu/AdminReportsView.swift` — admin",
          "`Views/Menu/AnimatedScreenDebugView.swift` — debug",
          "`Views/Menu/BackgroundReplacerView.swift` — user (seller tooling)",
          "`Views/Menu/BlackScreenProfileView.swift` — debug",
          "`Views/Menu/BlackScreensMenuView.swift` — debug",
          "`Views/Menu/CancelOrderView.swift` — user",
          "`Views/Menu/ChatThreadLiveUpdateDebugView.swift` — debug",
          "`Views/Menu/DashboardView.swift` — user",
          "`Views/Menu/DebugLikeButtonOnlyView.swift` — debug",
          "`Views/Menu/DebugLookbookFeedSandboxView.swift` — debug",
          "`Views/Menu/DebugMenuView.swift` — debug",
          "`Views/Menu/DebugSandboxLikeButton.swift` — debug",
          "`Views/Menu/FeedNetworkBannerDebugView.swift` — debug",
          "`Views/Menu/GlassEffectTransitionView.swift` — debug",
          "`Views/Menu/GlassMaterialsView.swift` — debug",
          "`Views/Menu/HelpChatView.swift` — user",
          "`Views/Menu/HowToUseWearhouseView.swift` — user",
          "`Views/Menu/InviteFriendView.swift` — user",
          "`Views/Menu/LegalInformationView.swift` — user",
          "`Views/Menu/LegalLeafViews.swift` — user",
          "`Views/Menu/ListOfContactsView.swift` — user",
          "`Views/Menu/LookbooksUploadView.swift` — user",
          "`Views/Menu/MenuView.swift` — user",
          "`Views/Menu/MessageChatPushTraceDebugView.swift` — debug",
          "`Views/Menu/MessageDeliveryDebugView.swift` — debug",
          "`Views/Menu/MultiBuyDiscountView.swift` — user",
          "`Views/Menu/MyFavouritesView.swift` — user",
          "`Views/Menu/MyOrdersView.swift` — user",
          "`Views/Menu/NetworkErrorPresentationDebugView.swift` — debug",
          "`Views/Menu/NotificationTypeMatrixDebugView.swift` — debug",
          "`Views/Menu/OrderChatMockDebugView.swift` — debug",
          "`Views/Menu/OrderDetailView.swift` — user",
          "`Views/Menu/OrderScreenDebugView.swift` — debug",
          "`Views/Menu/ProfileCardsComponentsView.swift` — component",
          "`Views/Menu/PushDiagnosticsView.swift` — debug",
          "`Views/Menu/RefundOrderView.swift` — user",
          "`Views/Menu/ShopToolsView.swift` — user",
          "`Views/Menu/ShopValueView.swift` — user",
          "`Views/Menu/VacationModeView.swift` — user",
          "`Views/Menu/WebSocketConnectionDebugView.swift` — debug",
          "`Views/Menu/WithdrawalFlowView.swift` — user",
          "`Views/Notifications/LikedItemSoldSimilarView.swift` — user",
          "`Views/Notifications/NotificationsListView.swift` — user",
          "`Views/Onboarding/LookbooksOnboardingView.swift` — user",
          "`Views/Onboarding/OnboardingFlowView.swift` — user",
          "`Views/Onboarding/OnboardingView.swift` — user",
          "`Views/Onboarding/TryCartOnboardingView.swift` — user",
          "`Views/Payment/PaymentSuccessfulView.swift` — user",
          "`Views/Payment/PaymentView.swift` — user",
          "`Views/Profile/FollowersListView.swift` — user",
          "`Views/Profile/FollowingListView.swift` — user",
          "`Views/Profile/MenuDestination.swift` — component (routing enum)",
          "`Views/Profile/MultiBuyCartView.swift` — user",
          "`Views/Profile/ProfileMenuView.swift` — user",
          "`Views/Profile/ProfileView.swift` — user",
          "`Views/Profile/ReviewsView.swift` — user",
          "`Views/Profile/SortSheetContent.swift` — component",
          "`Views/Profile/UserProfileView.swift` — user",
          "`Views/Report/ReportUserView.swift` — user",
          "`Views/Sell/HashtagHighlightingTextEditor.swift` — component",
          "`Views/Sell/SellFormRow.swift` — component",
          "`Views/Sell/SellLabeledField.swift` — component",
          "`Views/Sell/SellView.swift` — user",
          "`Views/Settings/AccountSettingsView.swift` — user",
          "`Views/Settings/AddBankAccountView.swift` — user",
          "`Views/Settings/AddPaymentCardView.swift` — user",
          "`Views/Settings/AdminMenuView.swift` — admin",
          "`Views/Settings/AppearanceMenuView.swift` — user",
          "`Views/Settings/BlocklistView.swift` — user",
          "`Views/Settings/CurrencySettingsView.swift` — user",
          "`Views/Settings/DeleteAccountView.swift` — user",
          "`Views/Settings/EmailChangeVerificationView.swift` — user",
          "`Views/Settings/LanguageMenuView.swift` — user",
          "`Views/Settings/MyReportsView.swift` — user",
          "`Views/Settings/NotificationSettingsView.swift` — user",
          "`Views/Settings/PauseAccountView.swift` — user",
          "`Views/Settings/PaymentSettingsView.swift` — user",
          "`Views/Settings/PostageSettingsView.swift` — user",
          "`Views/Settings/PrivacySettingsView.swift` — user",
          "`Views/Settings/ProfileSettingsView.swift` — user",
          "`Views/Settings/ResetPasswordView.swift` — user",
          "`Views/Settings/SecurityMenuView.swift` — user",
          "`Views/Settings/ShippingAddressView.swift` — user",
          "`Views/Settings/VerifyIdentityView.swift` — user",
          "`Views/SplashView.swift` — user"
        ]
      }
    ]
  },
  {
    "id": "manifest-4-modals-sheets-and-full-screen-covers-grep-snapshot",
    "title": "4. Modals, sheets, and full-screen covers (grep snapshot)",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Parent views that present overlays (for help: “where does this appear?”). Compiled from repository grep; not exhaustive for every `alert` string."
      },
      {
        "type": "table",
        "headers": [
          "Parent file",
          "Presentations"
        ],
        "rows": [
          [
            "`Prelura_swiftApp.swift`",
            "`fullScreenCover` deep link item; onboarding"
          ],
          [
            "`AppearanceRootView` (same file)",
            "onboarding, deep link"
          ],
          [
            "`HomeView.swift`",
            "`fullScreenCover` guest sign-in; `navigationDestination` notifications"
          ],
          [
            "`DiscoverView.swift`",
            "`fullScreenCover` search members, guest sign-in"
          ],
          [
            "`FilteredProductsView.swift`",
            "`sheet` (active sheet enum); `fullScreenCover` guest prompt"
          ],
          [
            "`ShopAllBagView.swift`",
            "`fullScreenCover` payment"
          ],
          [
            "`ItemDetailView.swift`",
            "full-screen images; guest prompt; send offer; options; report; edit listing; `navigationDestination` payment; delete/mark-sold alerts"
          ],
          [
            "`SellView.swift`",
            "upload failure alert; drafts sheet; draft saved; category picker"
          ],
          [
            "`ChatDetailView.swift`",
            "reaction sheet; counter-offer; `fullScreenCover` pay now; report sheet; folder error alert; seller options; cancel order alert"
          ],
          [
            "`LookbookView.swift`",
            "multiple comment/search/share sheets; `confirmationDialog`"
          ],
          [
            "`LookbooksUploadView.swift`",
            "crop flow, tag screen `fullScreenCover`; product picker `sheet`; `navigationDestination` item detail"
          ],
          [
            "`OrderDetailView.swift`",
            "tracking web; multibuy problem picker; feedback; confirm shipping `sheet`; order help `navigationDestination`"
          ],
          [
            "`MenuView.swift`",
            "logout confirm `alert`"
          ],
          [
            "`HelpChatView.swift`",
            "issue image viewer `fullScreenCover`"
          ],
          [
            "`AdminOrderIssuesView.swift`",
            "reply/action `sheet`"
          ],
          [
            "`ProfileView.swift`",
            "photo alert; bio sheet; listings sheet; nested `AppRoute`"
          ],
          [
            "`UserProfileView.swift`",
            "bio sheet; listings sheet"
          ],
          [
            "`AccountSettingsView.swift`",
            "date/gender sheets; email/phone verification sheets; saved alert"
          ],
          [
            "`LoginView.swift`",
            "forgot password `sheet`; email verification `fullScreenCover`; `navigationDestination` signup"
          ],
          [
            "`PaymentView.swift`",
            "payment success `fullScreenCover`"
          ],
          [
            "`AIChatView.swift`",
            "guest sign-in `fullScreenCover`"
          ],
          [
            "`AnnChatView.swift`",
            "order help `sheet`"
          ],
          [
            "`MultiBuyCartView.swift`",
            "payment `fullScreenCover`"
          ],
          [
            "`ShopValueView.swift`",
            "withdrawal flow `sheet`"
          ],
          [
            "`Settings/*`",
            "various save/confirm dialogs (`PaymentSettingsView`, `DeleteAccountView`, `PauseAccountView`, `BlocklistView`, `Add*` views, etc.)"
          ],
          [
            "`AdminDashboardView.swift`",
            "delete user sheet; multiple destructive confirms"
          ]
        ]
      }
    ]
  },
  {
    "id": "manifest-5-services-and-cross-cutting-capabilities",
    "title": "5. Services and cross-cutting capabilities",
    "blocks": [
      {
        "type": "paragraph",
        "text": "Files under [`Prelura-swift/Services/`](Prelura-swift/Services/) (help-centre topics often map here even without a dedicated screen):"
      },
      {
        "type": "table",
        "headers": [
          "Service",
          "Topics for help articles"
        ],
        "rows": [
          [
            "`AuthService`",
            "Login, guest mode, tokens, onboarding flags, account restriction"
          ],
          [
            "`AppRouter`",
            "Universal links, notification taps, `prelura://` URLs"
          ],
          [
            "`UserService`",
            "Profile, vacation mode, multibuy, moderation, FCM token, orders, cancellations"
          ],
          [
            "`ProductService`",
            "Listings, search, discovery"
          ],
          [
            "`ChatService` / `ChatWebSocketService` / `ConversationsWebSocketService`",
            "Messaging, typing, inbox sync"
          ],
          [
            "`NotificationService`",
            "Push categories, in-app notification list"
          ],
          [
            "`Payment` flows (via views + API)",
            "Delivery types, collection point, refunds"
          ],
          [
            "`FileUploadService`",
            "Listing photos"
          ],
          [
            "`LookbookService` / `LookbookFeedStore` / `SavedLookbookFavoritesStore`",
            "Lookbook feed, saves"
          ],
          [
            "`ShopAllBagStore`",
            "Multi-seller bag / checkout"
          ],
          [
            "`SellDraftStore`",
            "Draft listings"
          ],
          [
            "`OpenAIService` / `AISearchService`",
            "Lenny / AI discover assistant copy"
          ],
          [
            "`AdminService`",
            "Staff tools"
          ],
          [
            "`BackgroundRemovalService` / `GarmentAnalysisService` / etc.",
            "Seller image tools (when exposed in UI)"
          ]
        ]
      }
    ]
  },
  {
    "id": "manifest-8-authoring-template-for-chatgpt-cms",
    "title": "8. Authoring template (for ChatGPT / CMS)",
    "blocks": [
      {
        "type": "paragraph",
        "text": "For each help article, fill:"
      },
      {
        "type": "code",
        "text": "Title: \nSlug: \nCategory: (Getting started | Buying | Selling | Account & settings | Orders & delivery | Payments & refunds | Lookbooks | Safety & reporting | Trust & badges)\nApp area: (tab + menu path)\nPrimary user roles: guest | buyer | seller  \nSummary (1–2 sentences): \nSteps (numbered): \nScreens mentioned: (Swift view names for internal traceability)\nRelated URLs: (Constants.help* or legal)\nFAQ: "
      },
      {
        "type": "h3",
        "text": "8.1 Suggested slugs (align with Constants)"
      },
      {
        "type": "list",
        "items": [
          "`help/how-to-use`",
          "`help/cancel-order`",
          "`help/refunds`",
          "`help/delivery`",
          "`help/order-shipped`",
          "`help/collection-point`",
          "`help/delivered-not-received`",
          "`help/vacation-mode`",
          "`help/lookbook-beta`",
          "`help/seller-dashboard`",
          "`help/orders`",
          "`help/favourites`",
          "`help/multi-buy-discounts`",
          "`help/invite-friend`",
          "`help/trusted-seller`"
        ]
      },
      {
        "type": "paragraph",
        "text": "Add net-new articles as you inventory (e.g. `help/offers-and-counteroffers`, `help/shop-all-multibuy`)."
      }
    ]
  },
  {
    "id": "manifest-9-revision-log",
    "title": "9. Revision log",
    "blocks": [
      {
        "type": "list",
        "items": [
          "**2026-04-12:** Initial inventory from `Prelura-swift` tree; modal grep; `helpCentreBaseURL` set to `https://help.mywearhouseapp.com` in `Constants.swift`.",
          "**2026-04-12:** Replaced grouped “simple list” with flat commercial **Step 1 / Step 2** feature guide (no category headings); order detail, withdraw, and cancellations placed after **Orders**.",
          "**2026-04-12:** `HelpCentreView` **More topics** lists Profile menu features (Lookbook beta → Invite Friend) per §“Open the Profile menu”, plus collection point / delivered-not-received / trusted seller; URLs added in `Constants.swift`.",
          "**2026-04-12:** **Web Help Centre** expanded in `prelura-admin-web` at `/help`: same sidebar + hero pattern, new hubs (`/help/orders-refunds`, `/help/profile-tools`, `/help/account-app`), “Browse by topic” index, and static articles under `/help/[slug]` for every `Constants.help*` slug (see `src/lib/help-centre-articles.ts`, `src/lib/help-centre-nav.ts`)."
        ]
      }
    ]
  }
];
