/**
 * AUTO-GENERATED by scripts/generate-inventory-guide-data.mjs — do not edit by hand.
 * Source: PreluraSwift/HELP_CENTRE_FEATURE_INVENTORY.md (§6–§7).
 */

export const IN_APP_HELP_INTRO: string[] = [
  "After code update, articles load from **`helpCentreBaseURL`**:"
];

export const IN_APP_HELP_URL_ROWS: { constant: string; path: string }[] = [
  {
    "constant": "helpHowToUseWearhouseURL",
    "path": "/help/how-to-use"
  },
  {
    "constant": "helpArticleCancelOrderURL",
    "path": "/help/cancel-order"
  },
  {
    "constant": "helpArticleRefundsURL",
    "path": "/help/refunds"
  },
  {
    "constant": "helpArticleDeliveryURL",
    "path": "/help/delivery"
  },
  {
    "constant": "helpArticleOrderShippedURL",
    "path": "/help/order-shipped"
  },
  {
    "constant": "helpArticleCollectionPointURL",
    "path": "/help/collection-point"
  },
  {
    "constant": "helpArticleDeliveredNotReceivedURL",
    "path": "/help/delivered-not-received"
  },
  {
    "constant": "helpArticleVacationModeURL",
    "path": "/help/vacation-mode"
  },
  {
    "constant": "helpArticleLookbookBetaURL",
    "path": "/help/lookbook-beta"
  },
  {
    "constant": "helpArticleSellerDashboardURL",
    "path": "/help/seller-dashboard"
  },
  {
    "constant": "helpArticleOrdersURL",
    "path": "/help/orders"
  },
  {
    "constant": "helpArticleFavouritesURL",
    "path": "/help/favourites"
  },
  {
    "constant": "helpArticleMultiBuyDiscountsURL",
    "path": "/help/multi-buy-discounts"
  },
  {
    "constant": "helpArticleInviteFriendURL",
    "path": "/help/invite-friend"
  },
  {
    "constant": "helpArticleTrustedSellerURL",
    "path": "/help/trusted-seller"
  }
];

export const IN_APP_HELP_LEGAL_NOTE: string[] = [
  "Legal WebViews remain: `publicWebsiteBaseURL` + `/terms/`, `/privacy/`, `/acknowledgements/`.",
  "UI entry: [`HelpCentreView`](Prelura-swift/Views/Profile/ProfileMenuView.swift) lists FAQ + topics; **Start conversation** flows to Ann / support as implemented."
];

export const PERSONA_QA_INTRO: string = "Use this on device builds; the code cannot verify permissions copy or empty states.";

export const PERSONA_QA_GROUPS: { title: string; items: string[] }[] = [
  {
    "title": "Guest",
    "items": [
      "Home feed and item open; guest prompt when action requires account",
      "Discover / AI chat guest gating",
      "Shop All / filtered products guest gating",
      "Profile tab behaviour for guest (if applicable)",
      "Signup / login / forgot password / verification"
    ]
  },
  {
    "title": "Buyer",
    "items": [
      "Favourites; Shop All bag; multi-buy cart; payment success path",
      "Offers and counter-offers in chat; Pay now flow",
      "Orders list (purchases); order detail; tracking web view; feedback; cancel/refund flows where allowed",
      "Order issues: not received / not as described help wizards",
      "Notifications list and deep links",
      "Reviews on seller profiles",
      "Report user / listing options",
      "Block list behaviour"
    ]
  },
  {
    "title": "Seller",
    "items": [
      "Sell: new listing, drafts, category picker, upload errors, copy listing (if present in options)",
      "Seller dashboard / shop value / withdrawals",
      "Postage and payment settings",
      "Vacation mode (on/off, discover exclusion)",
      "Multi-buy discounts configuration",
      "Orders (sold); confirm shipping; seller-side cancellations / issues",
      "Lookbook beta: create/upload, settings, analytics navigation",
      "Background replacer / seller tools if user-facing"
    ]
  },
  {
    "title": "Admin / staff",
    "items": [
      "`AdminMenuView` and each linked admin screen",
      "Order issues / reports / dashboard destructive actions (document internally only)"
    ]
  },
  {
    "title": "Cross-cutting",
    "items": [
      "Onboarding and Try Cart / Lookbooks onboarding",
      "Appearance (light/dark/system) and language change behaviour",
      "Account pause and delete",
      "Identity verification flow",
      "Support chat branding (`WearhouseSupportBranding` — system support username)",
      "Account restriction overlay messaging",
      "Push notification permission and diagnostics (**do not** document debug screens to end users)"
    ]
  }
];
