/**
 * AUTO-GENERATED by scripts/generate-inventory-guide-data.mjs — do not edit by hand.
 * Source: PreluraSwift/HELP_CENTRE_FEATURE_INVENTORY.md (Simple feature list).
 */

export type InventoryGuideFeature = {
  id: string;
  title: string;
  why: string;
  steps: string[];
  expect?: string;
  goodToKnow?: string;
};

export type InventoryGuideGroup = {
  title: string;
  items: InventoryGuideFeature[];
};

export const INVENTORY_GUIDE_GROUPS: InventoryGuideGroup[] = [
  {
    "title": "Getting started",
    "items": [
      {
        "id": "sign-up",
        "title": "Sign up",
        "why": "Creates your WEARHOUSE account so you can buy, sell, save favourites, and message sellers with full trust and order history.",
        "steps": [
          "Open the app. If you are not signed in, you will see the **Welcome back** login screen.",
          "Under the form, tap **Sign up**.",
          "Complete the registration fields on the sign-up screen and submit.",
          "If the app asks you to verify your email, complete that step before shopping or listing."
        ],
        "expect": "After successful sign-up you may go straight into the main app or into **first-time onboarding**, depending on your account state.",
        "goodToKnow": "Use the **username** you register with when you log in later (not only your email display name)."
      },
      {
        "id": "log-in",
        "title": "Log in",
        "why": "Restores your account, orders, chats, listings, and saved items on this device.",
        "steps": [
          "From the **Welcome back** screen, enter your **Username** and **Password**.",
          "Tap **Login**.",
          "If you see an error about verification, use **Enter verification code** when it appears, or open email verification from the flows the app offers."
        ],
        "expect": "Successful login takes you to the main experience with five bottom tabs: **Home**, **Discover**, **Sell**, **Inbox**, **Profile**."
      },
      {
        "id": "guest-browsing",
        "title": "Guest browsing",
        "why": "Lets new visitors explore WEARHOUSE before committing to an account.",
        "steps": [
          "On the **Welcome back** screen, tap **Continue as guest**.",
          "Browse **Home** and **Discover** as normal.",
          "When you try to check out, message a seller, or another members-only action, the app will prompt you to sign in or create an account."
        ],
        "expect": "The **Profile** tab shows a sign-in prompt instead of your shop until you register or log in."
      },
      {
        "id": "forgot-password",
        "title": "Forgot password",
        "why": "Gets you back into your account if you cannot remember your password.",
        "steps": [
          "On the **Welcome back** screen, tap **Forgot password?**",
          "Follow the on-screen flow (email or reset steps as shown).",
          "Set a **New password** when directed, then return to **Login** and sign in."
        ],
        "goodToKnow": "Keep your username handy; you will need it together with the new password."
      },
      {
        "id": "email-and-account-verification",
        "title": "Email and account verification",
        "why": "Confirms you own the contact details on your account and unlocks full marketplace features when WEARHOUSE requires it.",
        "steps": [
          "If login shows an error mentioning email verification, tap **Enter verification code** when offered, or open the verification screen from the sign-up or account flows.",
          "Enter the code sent to your email (or complete the steps shown).",
          "After success, continue to **Login** or the app may proceed into onboarding."
        ],
        "expect": "Verification may also appear when you change email in **Settings** under **Account**."
      },
      {
        "id": "first-time-onboarding",
        "title": "First-time onboarding",
        "why": "Orients you to how WEARHOUSE works—shopping, cart ideas, and lookbooks—so you get value from day one.",
        "steps": [
          "After your first successful sign-in (or verification), a full-screen onboarding story appears automatically when applicable.",
          "Swipe or tap through each page.",
          "Finish the flow to reach the main tabs."
        ],
        "goodToKnow": "Onboarding can include **Try Cart** and **Lookbooks** highlights; it only shows when the app marks you as needing it."
      },
      {
        "id": "account-restriction-moderation",
        "title": "Account restriction (moderation)",
        "why": "Keeps the community safe; tells you clearly if your account has limited access while a review is in progress.",
        "steps": [
          "If your account is restricted, a full-screen message appears over the app after you sign in.",
          "Read the message and follow any instructions (e.g. contact support, check email).",
          "When the restriction is lifted, opening the app again will return you to normal use."
        ],
        "goodToKnow": "You do not reach this through a menu—it appears automatically when it applies."
      }
    ]
  },
  {
    "title": "Home & Discover",
    "items": [
      {
        "id": "home-feed-and-categories",
        "title": "Home feed and categories",
        "why": "This is your main window into new listings and featured pieces tailored to how people shop on WEARHOUSE.",
        "steps": [
          "Tap the **Home** tab (house icon) in the bottom bar.",
          "Scroll the feed to browse products.",
          "Use the horizontal category chips (e.g. **All**, **Women**, **Men**, **Boys**, **Girls**, **Toddlers**) to filter the feed.",
          "Pull down to refresh when you want the latest listings."
        ],
        "expect": "Featured sections and the product grid update when you change category or refresh."
      },
      {
        "id": "home-search",
        "title": "Home search",
        "why": "Finds specific items or styles quickly from the main feed.",
        "steps": [
          "On **Home**, tap the search field at the top of the feed.",
          "Type what you are looking for and submit search.",
          "Open any product from the results.",
          "If the app shows a close-match hint under the field, read it—it may suggest a better spelling or category."
        ]
      },
      {
        "id": "home-notifications-bell",
        "title": "Home notifications (bell)",
        "why": "Surfaces activity that needs your attention—messages, orders, and social signals—in one place.",
        "steps": [
          "On **Home**, tap the **bell** icon in the top-right of the navigation bar.",
          "Read the **Notifications** list.",
          "Tap an item to open the relevant chat, listing, or context."
        ],
        "expect": "A badge on the bell can show unread activity when present."
      },
      {
        "id": "ai-shopping-chat-from-home",
        "title": "AI shopping chat (from Home)",
        "why": "Lets you describe what you want in plain language and get guided toward relevant fashion on WEARHOUSE.",
        "steps": [
          "Stay on the **Home** tab.",
          "In the search row, tap the **AI** control (next to the search field).",
          "Chat with the assistant; follow suggestions or searches it proposes.",
          "Open products it surfaces, or refine what you type."
        ],
        "goodToKnow": "Some actions may ask you to sign in if you are browsing as a guest."
      },
      {
        "id": "discover-browsing-and-try-cart-shop-all",
        "title": "Discover browsing and Try Cart (Shop All)",
        "why": "Discover is built for exploration—brands, curated rows, and the **Try Cart** entry to **Shop All**, a powerful multi-item browse mode.",
        "steps": [
          "Tap the **Discover** tab (magnifying glass icon).",
          "Scroll to explore sections such as **Women** / **Men** rows, **Recently viewed**, **Brands You Love**, bargains, and more—tap a row to open that listing experience.",
          "Tap the large **Try Cart** banner (animated “Try Cart” text) to open **Shop All**.",
          "In **Shop All**, use categories, search, and filters; open the **bag** when you are ready to review items from multiple sellers."
        ],
        "expect": "**Shop All** is labeled **BETA** on the banner; inside, you can add to a shared bag and move toward checkout."
      },
      {
        "id": "discover-search-and-member-search",
        "title": "Discover search and member search",
        "why": "Finds both products and people—so you can shop a brand’s vibe or go straight to a seller you know.",
        "steps": [
          "On **Discover**, use the **Discover** search field at the top.",
          "Enter a query and submit.",
          "For **people**, when the app opens **member search** results (full screen), tap a member to view their profile and listings.",
          "For **products**, open items from filtered listing screens linked from pills, categories, or sections."
        ],
        "goodToKnow": "A **heart** icon in the **Discover** top bar opens **Favourites** directly."
      }
    ]
  },
  {
    "title": "Shopping & checkout",
    "items": [
      {
        "id": "product-detail-buyer-path",
        "title": "Product detail (buyer path)",
        "why": "This is the purchase decision screen—photos, story, price, seller, and how you buy or negotiate.",
        "steps": [
          "From **Home**, **Discover**, **Profile**, or search results, tap any product card.",
          "Read photos, title, description, and price.",
          "Switch between **Member’s items** and **Similar items** where tabs appear.",
          "Use **Buy now** to check out, or **Send an offer** if you want to negotiate.",
          "Tap the seller area to open their **Profile** when you want more from the same closet."
        ]
      },
      {
        "id": "product-photos-full-screen",
        "title": "Product photos (full screen)",
        "why": "Lets buyers inspect fabric, fit cues, and condition before they commit.",
        "steps": [
          "On the product page, tap the main image area.",
          "View images full screen; swipe between photos if there are several.",
          "Dismiss to return to the product page."
        ]
      },
      {
        "id": "like-and-save-an-item",
        "title": "Like and save an item",
        "why": "Builds a personal shortlist you can return to without losing the piece in the feed.",
        "steps": [
          "On a listing card or product page, tap the **heart** / like control.",
          "To see everything you saved, open **Profile** → **Menu** (three lines, top right) → **Favourites**, or use **Discover**’s top bar **heart** shortcut."
        ],
        "expect": "Liked items sync with your account for shopping later."
      },
      {
        "id": "shop-all-filtered-listings-and-bag",
        "title": "Shop All, filtered listings, and bag",
        "why": "Supports serious browsing—filters, categories, and a **bag** that can hold items from more than one seller before checkout.",
        "steps": [
          "Enter a filtered listing screen (e.g. **Shop All** from **Try Cart**, a **brand** pill, or a **category** row on **Discover**).",
          "Refine using search, filters, and category chips as shown on that screen.",
          "Tap **Add to bag** (or equivalent) on items you want.",
          "Open the **bag** icon / checkout entry on that flow to review lines and totals.",
          "Proceed to **Checkout** when you are ready; sign in if prompted as a guest."
        ],
        "goodToKnow": "Some Shop All flows may restrict offers; pay attention to on-screen buying options."
      },
      {
        "id": "multi-buy-from-a-seller-s-profile",
        "title": "Multi-buy from a seller’s profile",
        "why": "Rewards buying multiple pieces from the same closet—often combined with that seller’s **Multi-buy discounts** rules.",
        "steps": [
          "Open **Profile** (your shop or another member’s profile via product or search).",
          "When listings are visible, tap **Multi-buy** to enter selection mode.",
          "Tap listings to select them; selected items show a **Select** marker.",
          "When at least two items are selected, tap the floating **Shopping bag** button.",
          "Review **Multi-buy** checkout for that seller and complete payment when ready."
        ],
        "expect": "With only one item selected, the bag button stays inactive—pick at least two."
      },
      {
        "id": "make-an-offer",
        "title": "Send an offer",
        "why": "Lets buyers ask for a fair price and lets sellers close deals without re-listing.",
        "steps": [
          "Open the product page (not your own listing).",
          "Tap **Send an offer** (or open the offer flow from the product actions).",
          "Enter your offer amount and send.",
          "Go to **Inbox** to see the seller’s reply: accept, decline, or counter.",
          "If accepted, complete payment from the chat or product flow when the app prompts you."
        ]
      },
      {
        "id": "buy-checkout-and-delivery-choice",
        "title": "Buy, checkout, and delivery choice",
        "why": "Completes the purchase with clear delivery expectations—home delivery or collection-style options when available.",
        "steps": [
          "From a product page or bag, tap **Buy now** / **Checkout**.",
          "Choose **delivery type** where offered (e.g. home delivery vs collection / pickup-style options).",
          "Confirm shipping details and payment method.",
          "Pay using the secure flow.",
          "Stay on the success screen or return to **Orders** via **Menu** to track the purchase."
        ],
        "goodToKnow": "Guest buyers may be asked to sign in or create an account before paying."
      },
      {
        "id": "payment-success",
        "title": "Payment success",
        "why": "Confirms your money moved and your order exists in the system.",
        "steps": [
          "After payment, the app shows a **success** state (full screen or sheet).",
          "Read any next steps (e.g. watch **Inbox** for the seller).",
          "Dismiss and open **Orders** under **Menu** if you want to see the new order card immediately."
        ]
      }
    ]
  },
  {
    "title": "Your shop, profile & menu",
    "items": [
      {
        "id": "listing-options-seller-on-your-own-item",
        "title": "Listing options (seller, on your own item)",
        "why": "Keeps your shop accurate—edit details, mark sold, remove mistakes, or duplicate a winner listing.",
        "steps": [
          "Open one of **your** listings from **Profile** or **Sell**.",
          "Tap the **options** / more control on the product (as shown on your listing).",
          "Choose **Edit listing**, **Mark as sold**, **Delete**, or **Copy to a new listing** when available.",
          "Confirm any destructive action if the app asks."
        ],
        "expect": "Buyers visiting your listing never see seller-only options."
      },
      {
        "id": "report-a-listing-or-user",
        "title": "Report a listing or user",
        "why": "Protects the community; flags fakes, abuse, or policy breaks for WEARHOUSE review.",
        "steps": [
          "On a product page or in chat, open **Report** from the available menu or sheet.",
          "Choose the reason and add detail.",
          "Submit. You may also track reports under **Settings** → **Security & Privacy** → **My reports** when that applies."
        ]
      },
      {
        "id": "your-profile-tab-your-shop-window",
        "title": "Your Profile tab (your shop window)",
        "why": "This is your brand on WEARHOUSE—photo, bio, listings, reviews, and multi-buy entry.",
        "steps": [
          "Tap **Profile** (person icon) in the bottom bar.",
          "Scroll your header, bio, and listing grid.",
          "Use **Multi-buy**, filters, sort, and brand chips when you have active listings.",
          "Tap the **three horizontal lines** (top right) to open the **Menu** for orders, favourites, help, and more."
        ],
        "expect": "If **Vacation mode** is on, your shop shows a holiday message instead of products."
      },
      {
        "id": "edit-profile-photo-and-bio",
        "title": "Edit profile photo and bio",
        "why": "Builds trust—buyers buy from people who look real and descriptive.",
        "steps": [
          "Go to **Profile**.",
          "Tap your photo or the edit affordance the app shows on your avatar.",
          "Choose a new image from your library when the picker appears.",
          "For bio, tap your bio area or **See more** if truncated; update text in **Profile** settings or the sheet that opens, as guided."
        ],
        "goodToKnow": "Deep profile fields (name, birthday, etc.) also live under **Settings** → **Profile**."
      },
      {
        "id": "followers-and-following",
        "title": "Followers and following",
        "why": "Lets fans follow your drops and lets you follow closets you love.",
        "steps": [
          "Open a **Profile** (yours or another member’s).",
          "Tap **Following** or **Followers** counts.",
          "Browse the list; tap a user to open their profile.",
          "Use **Follow** / **Unfollow** on their profile when shown."
        ]
      },
      {
        "id": "reviews-on-your-profile",
        "title": "Reviews on your profile",
        "why": "Social proof that you ship fast and describe items honestly.",
        "steps": [
          "On **Profile**, tap the **reviews** row or rating area.",
          "Read feedback left by buyers.",
          "After you sell, complete any **leave feedback** prompts from **Orders** so your buyers can reciprocate over time."
        ]
      },
      {
        "id": "open-the-profile-menu-hamburger",
        "title": "Open the Profile menu (hamburger)",
        "why": "This is the control centre for selling, orders, discounts, vacation, help, and logout.",
        "steps": [
          "Tap **Profile** in the bottom bar.",
          "Tap the **three horizontal lines** icon in the top-right corner.",
          "You will see the **Menu** list: **Lookbook**, **Seller dashboard**, **Orders**, **Favourites**, **Multi-buy discounts**, **Vacation Mode**, **Invite Friend**, **Help Centre**, **About WEARHOUSE**, and **Logout**.",
          "Tap any row to go there.",
          "To reach **Settings**, tap the **gear** icon in the top-right of this **Menu** screen."
        ]
      },
      {
        "id": "lookbook-beta",
        "title": "Lookbook (beta)",
        "why": "A social-style layer for outfits and inspiration, tied to real items you can buy.",
        "steps": [
          "Open **Menu** from **Profile** (steps above).",
          "Tap **Lookbook** (shown with a **Beta** label).",
          "Scroll the feed, open posts, like, comment, or share as the app allows.",
          "Create or upload content from the Lookbook flows when you are a seller or creator (upload, tag products, publish)."
        ],
        "goodToKnow": "Lookbook complements your grid—it does not replace normal listings."
      },
      {
        "id": "seller-dashboard-shop-value",
        "title": "Seller dashboard (Shop value)",
        "why": "Shows how your shop is performing and connects earnings-oriented actions.",
        "steps": [
          "Open **Menu** from **Profile**.",
          "Tap **Seller dashboard**.",
          "Review sales-oriented metrics and shortcuts (e.g. withdrawals or tools your build exposes).",
          "Use on-screen buttons to drill into money movement or seller utilities."
        ]
      },
      {
        "id": "orders-bought-and-sold",
        "title": "Orders (bought and sold)",
        "why": "One place to track everything you are buying and selling.",
        "steps": [
          "Open **Menu** from **Profile**.",
          "Tap **Orders**.",
          "Switch between **purchases** and **sales** using the control at the top of the list (e.g. segmented control).",
          "Tap an order to open **Order detail**—tracking, ship confirmation, issues, or feedback."
        ]
      },
      {
        "id": "order-detail-tracking-actions-feedback",
        "title": "Order detail (tracking, actions, feedback)",
        "why": "This is the operational heart of a purchase—where buyers watch delivery and sellers mark shipped.",
        "steps": [
          "Open **Menu** → **Orders**.",
          "Tap the order you want.",
          "As a **buyer**, open **tracking** when available, download labels if shown, and leave **feedback** after delivery.",
          "As a **seller**, tap **Confirm shipped** (or equivalent) when you post the parcel.",
          "Use **Help** or issue buttons on this screen if something is wrong."
        ],
        "expect": "Status labels change from paid to shipped, in transit, delivered, or refunded depending on the journey."
      },
      {
        "id": "withdraw-earnings-seller",
        "title": "Withdraw earnings (seller)",
        "why": "Moves your WEARHOUSE balance to your bank so cash is usable in the real world.",
        "steps": [
          "Open **Menu** → **Seller dashboard**.",
          "Start **Withdraw** or **Payout** from the controls shown (wording may match your app version).",
          "Confirm amount and destination account.",
          "Complete any security checks.",
          "Watch **Seller dashboard** or email for completion."
        ],
        "goodToKnow": "You must have a valid payout method under **Settings** → **Payments**."
      },
      {
        "id": "cancellations-and-refunds-buyer-and-seller",
        "title": "Cancellations and refunds (buyer and seller)",
        "why": "Fair exit paths when plans change or an item cannot ship.",
        "steps": [
          "Open **Orders** and select the order.",
          "Tap **Cancel order** or the refund / cancellation entry if shown.",
          "Choose a reason when prompted.",
          "Confirm; both parties see updated status in **Orders** and **Inbox**.",
          "If money already moved, follow refund timing explained in **Help Centre** articles."
        ],
        "goodToKnow": "Not every stage allows cancellation—options depend on order state."
      },
      {
        "id": "favourites",
        "title": "Favourites",
        "why": "Your saved wishlist across WEARHOUSE.",
        "steps": [
          "Open **Menu** → **Favourites**, **or** tap the **heart** on **Discover**’s top bar.",
          "Scroll saved items.",
          "Tap any item to open the product page or remove from favourites as the UI allows."
        ]
      },
      {
        "id": "multi-buy-discounts-seller-setting",
        "title": "Multi-buy discounts (seller setting)",
        "why": "Encourages larger baskets from your closet with automatic savings rules you control.",
        "steps": [
          "Open **Menu** from **Profile**.",
          "Tap **Multi-buy discounts**.",
          "Turn rules on or off and set your tiers as the form shows.",
          "Save; buyers who meet the rules see better pricing at checkout."
        ],
        "expect": "The **Menu** row shows **On** or **Off** next to **Multi-buy discounts**."
      },
      {
        "id": "vacation-mode",
        "title": "Vacation Mode",
        "why": "Pauses your shop so buyers are not disappointed by delayed shipping while you are away.",
        "steps": [
          "Open **Menu** from **Profile**.",
          "Tap **Vacation Mode**.",
          "Toggle vacation on and save if prompted.",
          "Your **Profile** will show a holiday message and hide active listings from normal shopping until you return."
        ],
        "expect": "The **Menu** row shows **On** or **Off** for **Vacation Mode**."
      },
      {
        "id": "invite-a-friend",
        "title": "Invite a friend",
        "why": "Grows WEARHOUSE with people you already trust—and gives them a clean join path.",
        "steps": [
          "Open **Menu** → **Invite Friend**, **or** go **Settings** (gear on **Menu**) and open **Invite Friend** there too.",
          "Choose **Messages**, **Mail**, or another share channel from the share sheet.",
          "Send the invite link your friend can use to install and join."
        ]
      }
    ]
  },
  {
    "title": "About, legal & settings",
    "items": [
      {
        "id": "help-centre",
        "title": "Help Centre",
        "why": "Self-serve answers for orders, refunds, delivery, and trust—without waiting on email.",
        "steps": [
          "Open **Menu** → **Help Centre**.",
          "Use the search field (e.g. “change profile photo”) to filter topics.",
          "Under **Frequently asked** and **More topics**, tap a question to open the article in the in-app browser.",
          "For a guided chat, tap **Start a conversation** at the bottom to open **Ann** support chat."
        ],
        "expect": "Articles load from WEARHOUSE’s hosted help site; you need an internet connection."
      },
      {
        "id": "about-wearhouse-how-to-use",
        "title": "About WEARHOUSE — How to use",
        "why": "A single editorial overview of how the marketplace fits together for new members.",
        "steps": [
          "Open **Menu** → **About WEARHOUSE**.",
          "Tap **How to use WEARHOUSE**.",
          "Read the hosted article; scroll to the end, then use the back control to return."
        ]
      },
      {
        "id": "legal-information",
        "title": "Legal information",
        "why": "Transparent terms, privacy, and acknowledgements—you know the rules of the platform.",
        "steps": [
          "Open **Menu** → **About WEARHOUSE**.",
          "Tap **Legal Information**.",
          "Open **Terms**, **Privacy**, or **Acknowledgements** as listed.",
          "Read in the in-app web view; use **Back** to return to the list."
        ]
      },
      {
        "id": "logout",
        "title": "Logout",
        "why": "Ends your session on a shared or borrowed phone securely.",
        "steps": [
          "Open **Menu** from **Profile**.",
          "Scroll to **Logout** and tap it.",
          "Confirm in the dialog.",
          "You return to the **Welcome back** login screen."
        ]
      },
      {
        "id": "settings-gear-from-menu",
        "title": "Settings (gear from Menu)",
        "why": "Central place for account, money, shipping, appearance, notifications, and verification.",
        "steps": [
          "Open **Menu** from **Profile**.",
          "Tap the **gear** icon in the top-right corner of **Menu**.",
          "You will see **Settings** with rows such as **Profile**, **Account**, **Currency**, **Shipping**, **Appearance**, **Language**, **Payments**, **Security & Privacy**, **Identity verification**, **Lookbook settings**, **Push notifications**, **Email notifications**, and **Invite Friend**."
        ]
      },
      {
        "id": "profile-settings",
        "title": "Profile settings",
        "why": "Controls how you present publicly—name, bio, and profile fields shoppers see.",
        "steps": [
          "**Profile** tab → **Menu** (three lines) → **gear** → **Settings**.",
          "Tap **Profile**.",
          "Update the fields shown; save when prompted."
        ]
      },
      {
        "id": "account-settings",
        "title": "Account settings",
        "why": "Holds core account data—contact methods and personal details tied to security.",
        "steps": [
          "**Settings** → **Account**.",
          "Edit details; if you change email or phone, complete any verification sheets that appear.",
          "Save; watch for confirmation alerts."
        ]
      },
      {
        "id": "currency",
        "title": "Currency",
        "why": "Shows prices and settles charges in the money that makes sense for you.",
        "steps": [
          "**Settings** → **Currency**.",
          "Select your preferred currency option.",
          "Confirm or save if required; return to shopping to see updated presentation."
        ]
      },
      {
        "id": "shipping-address",
        "title": "Shipping address",
        "why": "Default place your purchases ship when you check out.",
        "steps": [
          "**Settings** → **Shipping** → **Shipping Address**.",
          "Enter or edit your address fields.",
          "Save; use **Saved** confirmation as your signal it stuck."
        ]
      },
      {
        "id": "postage-seller",
        "title": "Postage (seller)",
        "why": "Tells buyers how you ship and powers correct postage options at checkout.",
        "steps": [
          "**Settings** → **Shipping** → **Postage**.",
          "Configure postage options your shop uses.",
          "Save changes before listing new items."
        ]
      },
      {
        "id": "appearance-light-dark-system",
        "title": "Appearance (light, dark, system)",
        "why": "WEARHOUSE should feel comfortable in any lighting or personal taste.",
        "steps": [
          "**Settings** → **Appearance**.",
          "Choose **Light**, **Dark**, or match **System**.",
          "The entire app updates to your choice."
        ]
      },
      {
        "id": "language",
        "title": "Language",
        "why": "Lets you use WEARHOUSE in the language you read best when translations are available.",
        "steps": [
          "**Settings** → **Language**.",
          "Pick a language.",
          "If the app tells you to restart, close WEARHOUSE fully and reopen."
        ]
      },
      {
        "id": "payments-cards-and-bank",
        "title": "Payments (cards and bank)",
        "why": "You need a way to pay for purchases and, for sellers, to receive payouts.",
        "steps": [
          "**Settings** → **Payments**.",
          "Add a **card** or **bank account** using the **Add** flows.",
          "Remove methods with the remove / delete controls when allowed.",
          "Confirm any dialogs about removing a payout method."
        ],
        "expect": "Checkout and withdrawals use the methods you keep on file."
      },
      {
        "id": "security-and-privacy",
        "title": "Security and Privacy",
        "why": "Password hygiene, blocking, pausing, or deleting your presence safely.",
        "steps": [
          "**Settings** → **Security & Privacy**.",
          "Open **My reports** to see flags you filed.",
          "Open **Blocklist** to manage blocked members.",
          "Use **Reset Password** to change password while logged in.",
          "Use **Delete Account** or **Pause Account** only when you understand they are serious actions—confirm every warning."
        ]
      },
      {
        "id": "identity-verification",
        "title": "Identity verification",
        "why": "Unlocks higher-trust selling and payouts when WEARHOUSE or regulations require it.",
        "steps": [
          "**Settings** → **Identity verification**.",
          "Complete each step the flow requests (documents or selfies as shown).",
          "Wait for status updates in the app or email."
        ]
      },
      {
        "id": "lookbook-settings",
        "title": "Lookbook settings",
        "why": "Tunes how your Lookbook presence behaves alongside your listings.",
        "steps": [
          "**Settings** → **Lookbook settings**.",
          "Adjust preferences shown (visibility, notifications, or related toggles per your build).",
          "Save if prompted."
        ]
      },
      {
        "id": "push-notification-preferences",
        "title": "Push notification preferences",
        "why": "Controls which events buzz your phone—messages, sales, or marketing.",
        "steps": [
          "**Settings** → **Push notifications**.",
          "Toggle categories or topics as listed.",
          "If iOS shows system permission, allow alerts for WEARHOUSE so pushes can arrive."
        ]
      },
      {
        "id": "email-notification-preferences",
        "title": "Email notification preferences",
        "why": "Keeps important receipts and order mail without overwhelming your inbox.",
        "steps": [
          "**Settings** → **Email notifications**.",
          "Adjust categories as presented.",
          "Save if the screen requires it."
        ]
      }
    ]
  },
  {
    "title": "Sell, Inbox & support",
    "items": [
      {
        "id": "sell-tab-create-a-listing",
        "title": "Sell tab — create a listing",
        "why": "Turns clothes in your wardrobe into shoppable listings for thousands of buyers.",
        "steps": [
          "Tap **Sell** (plus icon) in the bottom bar.",
          "Add photos (camera or library).",
          "Fill title, description, **hashtags**, **category**, **size**, **condition**, **price**, and any optional AI or image tools offered.",
          "Tap publish / list when ready, or save as draft if you are not finished."
        ],
        "goodToKnow": "Large listings may take a moment to upload—stay on screen until confirmation."
      },
      {
        "id": "sell-tab-drafts",
        "title": "Sell tab — drafts",
        "why": "Lets you prepare listings when you have time and publish when lighting or pricing is final.",
        "steps": [
          "Go to **Sell**.",
          "Open **Drafts** (or the drafts entry your build shows on the Sell screen).",
          "Tap a draft to resume editing.",
          "Publish or delete drafts you no longer need."
        ]
      },
      {
        "id": "inbox-conversation-list",
        "title": "Inbox — conversation list",
        "why": "Every negotiation, order update, and buyer question lands here.",
        "steps": [
          "Tap **Inbox** (envelope icon) in the bottom bar.",
          "Scroll threads; unread counts may appear on the tab icon.",
          "Tap a thread to open the chat.",
          "Use any **Archived** entry point if you keep a separate archive list."
        ]
      },
      {
        "id": "inbox-chat-offers-and-pay-now",
        "title": "Inbox — chat, offers, and Pay now",
        "why": "This is where deals close—messages, offers, and payment prompts share one thread.",
        "steps": [
          "Open **Inbox** and choose a conversation.",
          "Type messages in the composer; send photos or taps as the UI allows.",
          "For offers, use **Accept**, **Decline**, or **Counter** on offer cards.",
          "When **Pay now** appears after a deal, tap it and complete payment in the flow that opens.",
          "Use **…** menus for extra actions (report, archive, seller tools)."
        ]
      },
      {
        "id": "inbox-archive-and-restore",
        "title": "Inbox — archive and restore",
        "why": "Clears mental clutter without losing message history.",
        "steps": [
          "Inside a chat, open the **more** / **…** menu in the navigation bar.",
          "Choose **Archive** (or equivalent).",
          "Open your **Archived** inbox list from **Inbox** when you need old threads.",
          "Open a thread and choose **Restore** when you want it back in the main list."
        ]
      },
      {
        "id": "order-help-and-issue-flows",
        "title": "Order help and issue flows",
        "why": "Structured paths for “item not received” or “not as described” so support can resolve fairly.",
        "steps": [
          "From **Orders** → open **Order detail**, **or** reach help from chat menus when tied to an order.",
          "Choose the issue type that matches your situation.",
          "Answer prompts honestly; upload photos if asked.",
          "Submit and watch **Inbox** or **Orders** for updates.",
          "For delivered-but-missing parcels, follow the **Item says Delivered** guidance linked from **Help Centre** if needed."
        ]
      },
      {
        "id": "ann-ai-support-chat",
        "title": "Ann — AI support chat",
        "why": "Fast, conversational answers plus order context without hunting articles.",
        "steps": [
          "Open **Help Centre** from **Menu**.",
          "Tap **Start a conversation**.",
          "Chat with **Ann**; ask about delivery, refunds, or account questions.",
          "Follow links or order rows she surfaces."
        ],
        "goodToKnow": "Ann complements human support; escalate in chat if your policy allows handoff."
      },
      {
        "id": "official-support-chat-thread",
        "title": "Official support chat thread",
        "why": "When automation is not enough, the WEARHOUSE support account can take the thread.",
        "steps": [
          "When you message platform support or open a support conversation, it appears in **Inbox** like any chat.",
          "The title may show as **Support Chat** for the official support identity.",
          "Send details, photos, and order IDs as requested."
        ]
      },
      {
        "id": "push-notifications-iphone",
        "title": "Push notifications (iPhone)",
        "why": "You never miss a sale, message, or shipment update.",
        "steps": [
          "When iOS asks, tap **Allow** for WEARHOUSE notifications.",
          "If you tapped **Don’t Allow** before, open **iPhone Settings** → **WEARHOUSE** → **Notifications** and enable them.",
          "Fine-tune categories inside WEARHOUSE under **Settings** → **Push notifications**."
        ],
        "expect": "Badges on **Inbox** and the **Home** bell reflect unread activity when enabled."
      },
      {
        "id": "open-from-links-and-notification-taps",
        "title": "Open from links and notification taps",
        "why": "Meets customers where they are—Instagram DMs, email, or SMS with a product link.",
        "steps": [
          "Tap a WEARHOUSE product or lookbook link on your iPhone with the app installed.",
          "iOS opens WEARHOUSE directly to that item or story when the link is supported.",
          "Tap a push notification about an order or message; the app routes to the right chat or listing."
        ],
        "goodToKnow": "If the app does not open, copy the link into Safari or update to the latest WEARHOUSE build."
      }
    ]
  }
];
